version: "3.8"

services:
  api:
    build: .
    container_name: blog-api
    ports:
      - "${PORT:-4000}:4000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: blog-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
